- name: Upgrade host packages
  become: yes
  apt:
    update_cache: yes
    upgrade: 'yes'
- name: Install basic apt necessities
  become: yes
  apt:
    update_cache: yes
    name:
    - sshpass
    - curl
    - unzip
    - jq
    - dnsutils
    - ntp
    - netcat
    - apt-transport-https
    - ca-certificates
    - gnupg
    - lsb-release
    - ffmpeg
    - python3
    - python3-pip
    - python3-venv
    - net-tools
    - moreutils
    state: present
    force_apt_get: yes

- name: Configure .bashrc with the default editor
  blockinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    marker: "# {mark} DEFAULT EDITOR"
    block: |
      export VISUAL="{{ default_editor_cmd }}"
      export EDITOR="${VISUAL}"
- name: Add Microsoft gpg signing key
  become: yes
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/microsoft.gpg
    state: present

